In [36]:
import numpy as np

y_true = np.array([1, 1, 2, 2, 1, 2, 1, 1, 2])
y_score = np.array([0.1, 0.4, 0.35, 0.8, 0.3, 0.2, 0.6, 0.25, 0.7])

pos_label = 2

y_true = (y_true == pos_label)

In [37]:
y_true

array([False, False,  True,  True, False,  True, False, False,  True], dtype=bool)

In [38]:
desc_score_indices = np.argsort(y_score)[::-1]

In [39]:
desc_score_indices

array([3, 8, 6, 1, 2, 4, 7, 5, 0])

In [40]:
y_score = y_score[desc_score_indices]

In [41]:
y_score

array([ 0.8 ,  0.7 ,  0.6 ,  0.4 ,  0.35,  0.3 ,  0.25,  0.2 ,  0.1 ])

In [44]:
y_true = y_true[desc_score_indices]

In [45]:
y_true

array([False, False, False,  True, False,  True,  True, False,  True], dtype=bool)

In [46]:
distinct_value_indices = np.where(np.diff(y_score))[0]

In [47]:
distinct_value_indices

array([0, 1, 2, 3, 4, 5, 6, 7])

In [48]:
threshold_idxs = np.r_[distinct_value_indices, y_true.size - 1]

In [49]:
threshold_idxs

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [50]:
tps = np.cumsum(y_true)[threshold_idxs]

In [51]:
tps

array([0, 0, 0, 1, 1, 2, 3, 3, 4])

In [52]:
fps = 1 + threshold_idxs - tps

In [53]:
fps

array([1, 2, 3, 3, 4, 4, 4, 5, 5])

In [54]:
fpr = fps / fps[-1]

In [55]:
fpr

array([ 0.2,  0.4,  0.6,  0.6,  0.8,  0.8,  0.8,  1. ,  1. ])

In [56]:
tpr = tps / tps[-1]

In [57]:
tpr

array([ 0.  ,  0.  ,  0.  ,  0.25,  0.25,  0.5 ,  0.75,  0.75,  1.  ])

In [33]:
threshold_idxs

array([0, 1, 2, 3])

In [34]:
tps

array([1, 1, 2, 2])

In [35]:
1 - tps

array([ 0,  0, -1, -1])